### PR TITLE
Fix cd error in test

### PR DESCRIPTION
**Pull request by kchodorow**
(See the Fix cd commit description.)

### CODE REVIEW

**Comment by kchodorow** [comment]
Note that this doesn't actually fix the error that we're getting on Jenkins.  It just fixes [this error](http://ci.bazel.io/job/PR-rules_dotnet/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/3/console):

```
/private/var/tmp/_bazel_ci/e305a8db68ed3b3e5540ded576293b6a/execroot/darwin-x86_64/bazel-out/local-fastbuild/bin/examples/example_test/MyTest.runfiles/io_bazel_rules_dotnet/examples/example_test/MyTest: line 3: cd: /private/var/tmp/_bazel_ci/e305a8db68ed3b3e5540ded576293b6a/execroot/darwin-x86_64/bazel-out/local-fastbuild/bin/examples/example_test/MyTest.runfiles/io_bazel_rules_dotnet/examples/example_test/MyTest.runfiles: No such file or directory
```

I'm actually pretty confused why this is failing:

```
____From Testing //examples/example_test:MyTest:
==================== Test output for //examples/example_test:MyTest:
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Unix 15.5.0.0
  CLR Version: 4.0.30319.17020 ( Mono 4.0 ( 4.2.3 (explicit/832de4b Thu Mar  3 19:24:57 EST 2016) ) )

File type not known: ../nunit/NUnit-2.6.4/bin/framework/nunit.framework.xml
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
================================================================================
```

It doesn't look like there are any errors there?

**Comment by kchodorow** [comment]
Jenkins, test this please.

**Comment by kchodorow** [comment]
Okay, so this does work on Darwin without the NUnit.Framework change.  Although the error is different than the "main" CI was getting (`execroot/external/mono/bin/mono: No such file or directory`), so... ?

**Comment by damienmg** [comment]
The problem with Darwin is that it use an external repository to declare it
deps so it just means the compiler isn't shipped in the sandbox. A rough
fix is to add a glob in the build file and ship everything in as an action
dep. I almost got that working last week then got side tracked with the fix
on CI and the Tutorial.

**Comment by kchodorow** [comment]
Is the PR jenkins disabling sandboxing or something?  Because this passes with that...

**Comment by damienmg** [comment]
PR vetting does not use bazel HEAD, only bazel release.

Also we have deactivated linux for dotnet because of #14

**Comment by damienmg** [comment]
So I had some time to work on this breakage today and we cannot fix it.

To fix it, we need to pass a filegroup of the files from the mono toolchain which contains spaces. Therefore those filename cannot be labels therefore cannot be included.

I see if we can just mark the action local for now.

**Comment by damienmg** [comment]
Ok of course this cannot be made because these are skylark action... I see only one solution for now: deactivate sandboxing for this ruleset. That's terribly sad :(

**Comment by kchodorow** [comment]
I think this change is still legit, mind if I merge it?

**Comment by damienmg** [comment]
LGTM 👍

**Pull request merged**
