### PR TITLE
Add build badge to README

### PR DESCRIPTION
**Pull request by j3parker**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by j3parker** [comment]
Jenkins, test this please.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by j3parker** [comment]
@philwo what triggers CI for this repo? Does an org member need to say the magic words?
(I don't care about CI on this one, just trying to understand.)

**Comment by philwo** [comment]
@j3parker To be honest, I'm not sure yet what triggers it ;) I've just inherited our Jenkins CI setup 2 weeks ago from its previous maintainer and am still reading the code and configs to see what it does.

I think, because rules_dotnet is setup as a project on our CI (https://ci.bazel.build/job/rules_dotnet/), Jenkins also checks pull requests and if you're on a whitelist, it will automatically test it and if you're not, it will ask "Can one of the admins verify this patch".

If I then say the magic words "Jenkins, test this please", it is supposed to actually test it. (This is to guard against random people sending "pull requests" on GitHub projects that actually start mining Bitcoins when executed on CI, or worse ;))

**Comment by philwo** [comment]
(Now that I mentioned the magic phrase, CI is running - I love it when things just work!)

**Comment by j3parker** [comment]
@philwo neat!

Would it be possible to add me to the whitelist or is it only Google employees? Would it have any other unwanted implications? I plan to/am submitting more PRs to these repos.

(I promise I'm not interested in bitcoins or otherwise messing with the infrastructure :) )

**Comment by philwo** [comment]
TBH, I'm not sure how the whitelist is currently configured (or how to change it) - I think it might be automatically restricted to @google.com addresses only. However, as I'm reworking parts of our CI setup, I'm happy to see if we can change this.

I've filed a feature request in our CI repo to track this. :)

**Comment by j3parker** [comment]
Thanks!

**Pull request merged**
