### PR TITLE
Hard fail when operating system is unknown.

### PR DESCRIPTION
**Pull request by pcj**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pcj** [comment]
@zaphar Somehow I keep forgetting that (obviously) linux is not supported.  Then I spend time trying to figure out why the build is failing (i.e., stopped excluding a csharp test on linux).

This at least informs the user better.  Let me know if there is a use-case for letting the autoconf try for best effort (which seems covered by use_local_mono=True).

**Comment by zaphar** [comment]
I need to think about this one a bit and I'm a bit time constrained at the moment so sorry for long latency responses here.

**Comment by pcj** [comment]
Sounds good.  The current behavior will try to find a local mono instance on the non-mac host (perhaps from something like apt-get install mono-complete).  This change would require a linux user to say `use_local_mono=True`.  

In the future this would not be an issue if rules_dotnet could download mono for linux.  I have not looked much into how complicated linux support is for rules_dotnet though.

**Pull request merged**
